language: python
python:
  - "3.4"
  - "3.5"
addons:
  firefox: "55.0.3"

#To go headless
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
#command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start

 #command to run tests
script:
  - py.test --cov

after_success:
  - bash <(curl -s https://codecov.io/bash)